### ISSUE TITLE
web: create a TODO app with different stacks

### ISSUE THREAD

**Issue by NenadPantelic** [NenadPantelic/cave-for-devs#10]
Create a  simple TODO app as the REST API with the CRUD functionalities by using different stacks:

API:
- [ ] Spring Boot
- [ ] Django
- [ ] Flask
- [ ] Express
- [ ] .NET Web API
- [ ] Ruby on Rails

UI:
- [ ]  React
- [ ] Angular
- [ ] Vue.js
- [ ] Svelte
- [ ] Ember

Databases:
- [ ] MySQL
- [ ] MS SQL Server
- [ ] PosgreSQL
- [ ] MongoDB

Notes:
1. Feel free to add other stack combinations
2. Add GraphQL alternative. The first contributor should create two folders: `rest-api` and `graphql` to separate projects
3. Add other functionalities (every project should have it's own README with the listed features) - auth, search....
